Google Lighthouse and W3C Validation Improvements
VIP-COLLAB/VIP-COLLAB.github.io pull request #1
Opened 2021-02-02 22:10 UTC by t51r

Implemented Google Lighthouse and W3C optimizations, including:
- Added HTML `lang` attribute, `charset` meta tag, and tweaked `viewport` meta tag
- Removed unnecessary style tag `type` attribute
- Added missing image `alt`, `width`, and `height` attributes
- Resized and compressed images
- Switched to hierarchical headers (H1 / H2) and adjusted CSS accordingly
- Added `aria-label` attributes to several items
- Fixed W3C validation issues with several missing or unnecessary element closing tags (most paragraphs and divs)

2021-02-02 23:32 UTC, didtheyvotein requested changes
Overall I think this is a lot of good cleanup & optimization. 

- We need to decide on a phrase besides "Address Verification Service". 
- The `h1` / `h2` use suggests hierarchy where there isn't any
- I prefer the white button text, but I can be convinced otherwise based on what others think

2021-02-02 23:32 UTC, didtheyvotein commented on about.html
> +<img id="logo" src="respect-small.png" alt="Residency Inspection logo." width="350" height="134" />
"Respect" is the company name; "Residency Inspection" is just text for the logo. (So, alt should be "Respect logo")

2021-02-02 23:32 UTC, didtheyvotein commented on about.html
> +<h1>Passionate about fairness.</h1>
All should be either h2 or h1 (headers are on same level -- "Passionate about fairness") isn't a title for the entire page

2021-02-02 23:32 UTC, didtheyvotein commented on banks.html
> +<meta name="description" content="Respect services offers residential and business address verification services that can help ensure the integrity of your customer identification program." />
We may wish to stick with the more concrete description that's on the Overview page. ("Address Verification Service" has a very specific meaning to financial institutions, and this text doesn't speak to schools.) But, we're still thinking of the least-clumsy way to describe this.

2021-02-02 23:32 UTC, didtheyvotein commented on banks.html
> +<title>Residential & Business Address Verification Services for Banks</title>
We do need a description of the service in the <title> - but AVS can't be it. (And company name "Respect" should probably stay.)

2021-02-02 23:32 UTC, didtheyvotein commented on walkthrough.html
> +<meta name="description" content="Discover the Respect Services process for submitting address verification requests, accessing and removing submitted data." />
See prior notes about "AVS"

2021-02-02 23:32 UTC, didtheyvotein commented on respect.css
> +  color: var(--purple);
Is there a reason for this?

2021-02-02 23:32 UTC, didtheyvotein commented on walkthrough.html
> +<title>Address Verification Service Walkthrough</title>
AVS

2021-02-02 23:36 UTC, t51r commented on respect.css
> +  color: var(--purple);
White on that background color has poor color contrast, and Lighthouse calls it out as an accessibility issue.

2021-02-02 23:40 UTC, t51r commented on about.html
> +<h1>Passionate about fairness.</h1>
By HTML spec, and from an SEO and accessibility standpoint, there should really be a single H1 per page. All other headers should be H2-H6. Generally I don't go beyond H2-3.

2021-02-02 23:46 UTC, t51r commented on about.html
> +<img id="logo" src="respect-small.png" alt="Residency Inspection logo." width="350" height="134" />
Changed all logo alt text to "Respect logo."

2021-02-02 23:48 UTC, t51r commented on banks.html
> +<title>Residential & Business Address Verification Services for Banks</title>
I'd typically recommend for title tags that we rear brand with a "pipe" for consistency sake:
e.g. "Residential & Business Blah Blah | Respect"

2021-02-02 23:54 UTC, t51r commented on banks.html
> +<meta name="description" content="Respect services offers residential and business address verification services that can help ensure the integrity of your customer identification program." />
Let me know what the preferred text is and I'll change it. Generally for meta descriptions I try to stick to ~156 characters or less.

2021-02-03 01:30 UTC, didtheyvotein commented on respect.css
> +  color: var(--purple);
OK - let's try the purple.

2021-02-03 01:31 UTC, didtheyvotein commented on banks.html
> +<title>Residential & Business Address Verification Services for Banks</title>
I like pipes.

2021-02-03 01:36 UTC, didtheyvotein commented on about.html
> +<h1>Passionate about fairness.</h1>
Perhaps we can keep them as `h2` on these small pages? (And then use `h1` on our content pages which have meaningful titles). It's not a big deal either way.

2021-02-03 01:37 UTC, didtheyvotein commented on banks.html
> +<meta name="description" content="Respect services offers residential and business address verification services that can help ensure the integrity of your customer identification program." />
Honestly a hard question :smile: "Address validation" is also taken (by USPS, UPS, etc.)

"Inspection" kinda has the right ring (not as intense as "investigation", but suggests more manual effort and fastidiousness than "processing" or "validation"). But it's not clear enough for a `meta` tag. 

Any thoughts?

2021-02-03 01:51 UTC, didtheyvotein commented on banks.html
> +<meta name="description" content="Respect services offers residential and business address verification services that can help ensure the integrity of your customer identification program." />
For the `title`, how about some formatting of "Respect: find address fraud while preserving privacy"?

For the `meta` tag, how about "Respect processes address databases (without attached names) to ensure that students belong to school districts and bank accounts have legitimate records." (We'll probably need to change this.)

2021-02-03 02:44 UTC, didtheyvotein approved these changes

2021-02-03 02:45 UTC, merged